export const colors = {
	COLOR_PRIMARY: "#00ADB5",
	COLOR_LIGHT: "#fff",
	COLOR_DARK: "#222831",
	COLOR_DARK_ALT: "#393E46",
};

export const categories = [
	{
		id: "01",
		category: "Sarapan",
	},
	{
		id: "02",
		category: "Makan Siang",
	},
	{
		id: "03",
		category: "Makan Malam",
	},
	{
		id: "04",
		category: "Asian",
	},
	{
		id: "05",
		category: "Desserts",
	},
	{
		id: "06",
		category: "Seafood",
	},
];

export const recipeList = [
	{
		id: "01",
		name: "Nasi Goreng",
		image: require("../assets/images/nasigoreng.png"),
		rating: "4.5",
		ingredients: ["Nasi", "Telur", "Bawang Merah", "Bawang Putih", "Kecap Manis", "Garam", "Merica", "Minyak Goreng"],
		time: "30 menit",
		difficulty: "Mudah",
		calories: "350 kalori",
		color: "#FF5733",
		description:
			"Nasi goreng adalah makanan khas Indonesia yang lezat dan mudah dibuat. Terdiri dari nasi yang digoreng bersama dengan telur, bawang merah, bawang putih, dan bumbu lainnya.",
		steps: [
			"Panaskan minyak goreng dalam wajan.",
			"Tumis bawang merah dan bawang putih hingga harum.",
			"Tambahkan telur dan aduk hingga setengah matang.",
			"Masukkan nasi dan aduk rata dengan bumbu.",
			"Tuangkan kecap manis dan aduk hingga merata.",
			"Tambahkan garam dan merica secukupnya.",
			"Aduk terus hingga nasi matang dan terasa gurih.",
			"Sajikan nasi goreng panas dengan acar dan kerupuk.",
		],
	},
	{
		id: "02",
		name: "Gado-Gado",
		image: require("../assets/images/gadogado.png"),
		rating: "4.5",
		ingredients: ["Kacang Panjang", "Kentang", "Tahu", "Tempe", "Kubis", "Bayam", "Timun", "Telur", "Bumbu Kacang", "Kerupuk", "Bawang Goreng"],
		time: "30 menit",
		difficulty: "Mudah",
		calories: "350 kalori",
		color: "#FFA500",
		description: "Gado-Gado adalah salah satu makanan khas Indonesia yang terdiri dari campuran sayuran segar seperti kacang panjang, kentang, tahu, tempe, dan lainnya, disajikan dengan bumbu kacang khas dan kerupuk.",
		steps: [
			"Rebus kacang panjang, kentang, tahu, tempe hingga matang.",
			"Potong sayuran seperti kubis, bayam, timun, dan telur, kemudian goreng telur.",
			"Siapkan bumbu kacang dengan cara menggiling kacang tanah, cabai, gula, garam, dan sedikit air.",
			"Susun sayuran dan telur di atas piring, tuangkan bumbu kacang, taburkan bawang goreng, dan tambahkan kerupuk.",
			"Nikmati Gado-Gado segar ini sebagai hidangan utama atau sampingan!",
		],
	},	
	{
		id: "03",
		name: "Hot Dog",
		image: require("../assets/images/hotdog.png"),
		rating: "4.6",
		ingredients: ["Roti Hot Dog", "Sosis Frankfurter", "Saus Tomat", "Mustard"],
		time: "15 menit",
		difficulty: "Sedang",
		calories: "420 kalori",
		color: "#FF0000",
		description: "Hot Dog adalah salah satu favorit klasik Amerika, roti hot dog yang diisi dengan sosis frankfurter yang juicy, disiram dengan saus tomat dan mustard untuk keseimbangan rasa yang sempurna.",
		steps: [
			"Panggang atau panaskan sosis frankfurter hingga matang.",
			"Letakkan sosis frankfurter di dalam roti hot dog.",
			"Siram saus tomat dan mustard di atas sosis frankfurter.",
			"Sajikan dengan sampingan favorit Anda dan nikmati!",
		],
	},	
	{
		id: "04",
		name: "Manchurian",
		image: require("../assets/images/manchurian.png"),
		rating: "3.6",
		ingredients: ["Kol", "Saus Kecap", "Jahe", "Bawang Putih"],
		time: "30 menit",
		difficulty: "Mudah",
		calories: "350 kalori",
		color: "#d35400",
		description: "Manchurian adalah hidangan populer Indo-Cina yang terdiri dari potongan kol yang renyah disiram dengan saus beraroma khas yang terbuat dari saus kecap, jahe, dan bawang putih.",
		steps: [
			"Potong kol menjadi kuntum dan blansir.",
			"Siapkan saus dengan mencampur saus kecap, jahe, dan bawang putih.",
			"Goreng kol dalam minyak panas hingga renyah.",
			"Campurkan kol goreng dengan saus hingga terbalut rata.",
			"Taburkan daun bawang cincang dan sajikan selagi hangat.",
		],
	},	
	{
		id: "05",
		name: "Cupcakes",
		image: require("../assets/images/cupcakes.png"),
		rating: "5.0",
		ingredients: ["Tepung", "Gula", "Telur", "Mentega"],
		time: "60 menit",
		difficulty: "Sedang",
		calories: "200 kalori",
		description: "Cupcakes yang lezat dibuat dengan campuran sempurna dari tepung, gula, telur, dan mentega, cocok untuk setiap kesempatan.",
		steps: [
			"Panaskan oven pada suhu tertentu.",
			"Siapkan adonan cupcakes dengan mencampur bahan-bahan bersama-sama.",
			"Alasi loyang muffin dengan kertas cupcake.",
			"Isi setiap cupcake dengan adonan dan panggang dalam oven.",
			"Biarkan cupcakes dingin, lalu hias dengan frosting sesuai selera.",
			"Nikmati kue manis ini dan rasakan kenikmatannya!",
		],
	},	
	{
		id: "06",
		name: "Ramen",
		image: require("../assets/images/ramen-org.png"),
		rating: "4.2",
		ingredients: ["Mie Ramen", "Kecap Asin", "Telur", "Sayuran"],
		time: "45 menit",
		difficulty: "Sedang",
		calories: "400 kalori",
		description: "Sebuah mangkuk ramen yang nyaman dengan mie yang enak, kaldu yang gurih berbahan dasar kecap asin, sayuran yang lembut, dan telur yang sempurna.",
		steps: [
			"Rebus mie ramen sesuai petunjuk pada kemasan.",
			"Dalam panci, panaskan air hingga mendidih lalu tambahkan kecap asin untuk kaldu.",
			"Tambahkan sayuran yang telah dicincang dan biarkan matang hingga lembut.",
			"Rebus telur sesuai selera, lalu kupas dan iris tipis.",
			"Susun mangkuk ramen dengan meletakkan mie rebus, sayuran, dan irisan telur.",
			"Tuangkan kaldu panas di atas bahan-bahan tersebut dan siapkan untuk menikmati ramen buatan sendiri!",
		],
	}	
];